name: workshop
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - private

  api:
    build: ./api
    container_name: api
    ports:
      - $PORT:$PORT
    depends_on:
      - mongodb
    env_file:
      - ./api/.env
    networks:
      - public
      - private
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  ui:
    build: ./ui
    container_name: ui
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - public

  nginx:
    container_name: nginx-certbot
    image: jonasal/nginx-certbot:5.2.1-nginx1.27.0
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./nginx/nginx-certbot.env
    configs:
      - source: api_config
        target: /etc/nginx/user_conf.d/api.conf
      - source: ui_config
        target: /etc/nginx/user_conf.d/ui.conf
    networks:
      - public
    volumes:
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - api
      - ui

volumes:
  mongodb_data:
  nginx_secrets:

networks:
  public:
  private:

configs:
  api_config:
    file: ./nginx/api.conf
  ui_config:
    file: ./nginx/ui.conf
